# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTableViewWithWS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTableViewWithWS
	pod 'SDWebImage', '~>3.8'
    pod 'UIActivityIndicator-for-SDWebImage'
  target 'SwiftTableViewWithWSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftTableViewWithWSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
